tasks:
  - name: astra-tiktok
    init: |
      cd /workspace/astra-tiktok 
      nvm install node
      npm install -g npm@latest
      npm install -g netlify-cli
    command: |
      cd /workspace/astra-tiktok
      echo "astra-tiktok gitpod ready - LET'S DO THIS!"
      npm install
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: open-preview
  - port: 3000
    onOpen: ignore    
